weightedGraph =[[
		{"node":1,"edgeWeight":3},
		{"node":2,"edgeWeight":4},
		{"node":3,"edgeWeight":5}
	],
	[
		{"node":0,"edgeWeight":3},
		{"node":2,"edgeWeight":6},
		{"node":4,"edgeWeight":2}
	],
	[
		{"node":0,"edgeWeight":4},
		{"node":1,"edgeWeight":6},
		{"node":3,"edgeWeight":4},
		{"node":4,"edgeWeight":7}
	],
	[
		{"node":0,"edgeWeight":5},
		{"node":2,"edgeWeight":4},
		{"node":4,"edgeWeight":8}
		],
	[
		{"node":1,"edgeWeight":2},
		{"node":2,"edgeWeight":7},
		{"node":3,"edgeWeight":8},
		{"node":5,"edgeWeight":1}
	],
	[
		{"node":4,"edgeWeight":1}
	]
]
	